# splitwise/models.py

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional

@dataclass(frozen=True) # frozen=True makes instances immutable and hashable by default
class User:
    """Represents a user in the Splitwise application."""
    user_id: str
    name: str

    # __eq__ and __hash__ are automatically generated by dataclass(frozen=True)
    # This ensures that User objects can be used as keys in dictionaries or elements in sets.